from __future__ import annotations

from io import BytesIO
import re
from datetime import datetime
from xml.sax.saxutils import escape

from openpyxl import Workbook
from openpyxl.styles import Alignment, Font
from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT, TA_RIGHT
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.units import mm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet

from .schemas import OrderWithItemsOut


_DATE_SUFFIX_RE = re.compile(r"\s-\s\d{2}-\d{2}-\d{4}$")


def safe_export_filename(name: str, ext: str) -> str:
    """Best-effort safe filename for Content-Disposition and browser downloads."""
    ext = ext.lstrip(".")
    base = (name or "").strip() or "order"
    # Replace forbidden / risky filename characters.
    base = re.sub(r"[\\/:*?\"<>|\n\r\t]", "_", base)
    base = re.sub(r"\s+", " ", base).strip().strip(".")
    if not base:
        base = "order"
    # Avoid absurdly long filenames.
    base = base[:120].rstrip()
    return f"{base}.{ext}"


def _fmt_date(dt: datetime) -> str:
    try:
        return dt.strftime("%d-%m-%Y")
    except Exception:
        return ""


def build_order_pdf(order: OrderWithItemsOut, workshop_name: str | None = None) -> bytes:
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=landscape(A4),
        leftMargin=12 * mm,
        rightMargin=12 * mm,
        topMargin=12 * mm,
        bottomMargin=12 * mm,
        title=f"Order {order.id}",
    )

    styles = getSampleStyleSheet()
    header_style = styles["Title"]
    header_style.fontSize = 16
    header_style.leading = 18

    normal_style = styles["Normal"]
    normal_style.fontSize = 10
    normal_style.leading = 12

    subtle_style = styles["Normal"].clone("Subtle")
    subtle_style.fontSize = 9
    subtle_style.leading = 11
    subtle_style.textColor = colors.grey

    cell_style = styles["Normal"].clone("Cell")
    cell_style.fontSize = 8
    cell_style.leading = 10
    cell_style.alignment = TA_LEFT
    # Force wrapping even for long/unbroken strings.
    cell_style.wordWrap = "CJK"
    cell_style.splitLongWords = 1

    cell_right_style = styles["Normal"].clone("CellRight")
    cell_right_style.fontSize = 8
    cell_right_style.leading = 10
    cell_right_style.alignment = TA_RIGHT
    cell_right_style.wordWrap = "CJK"
    cell_right_style.splitLongWords = 1

    header_cell_style = styles["Normal"].clone("HeaderCell")
    header_cell_style.fontSize = 8
    header_cell_style.leading = 10
    header_cell_style.alignment = TA_LEFT
    header_cell_style.wordWrap = "CJK"
    header_cell_style.splitLongWords = 1

    header_lines: list[Paragraph] = []
    title = order.order_name or f"Order {order.id}"
    if workshop_name:
        header_lines.append(Paragraph(f"<b>{escape(workshop_name)}</b>", header_style))
        header_lines.append(Paragraph(f"Order: {escape(title)}", normal_style))
    else:
        header_lines.append(Paragraph(f"<b>{escape(title)}</b>", header_style))
    header_lines.append(Paragraph(f"Date: {_fmt_date(order.created_at)}", normal_style))
    header_lines.append(Paragraph("Generated by Spare Parts Tracker", subtle_style))

    data: list[list[object]] = [
        [
            Paragraph("<b>Manufacturer</b>", header_cell_style),
            Paragraph("<b>Model</b>", header_cell_style),
            Paragraph("<b>Spare Part</b>", header_cell_style),
            Paragraph("<b>Required Quantity</b>", header_cell_style),
            Paragraph("<b>Typical Specification / Note</b>", header_cell_style),
            Paragraph("<b>OEM Part Number</b>", header_cell_style),
        ]
    ]

    def p(text: str, style) -> Paragraph:
        safe = escape(text or "")
        # Preserve intentional line breaks.
        safe = safe.replace("\r\n", "\n").replace("\r", "\n").replace("\n", "<br/>")
        return Paragraph(safe, style)

    for item in sorted(
        order.items,
        key=lambda x: (x.manufacturer_name.lower(), x.model_name.lower(), x.spare_part_name.lower()),
    ):
        data.append(
            [
                p(item.manufacturer_name, cell_style),
                p(item.model_name, cell_style),
                p(item.spare_part_name, cell_style),
                p(str(item.quantity), cell_right_style),
                p(item.typical_specification or "", cell_style),
                p(item.oem_part_number or "", cell_style),
            ]
        )

    # Landscape A4 width is 297mm; with 12mm margins on both sides, usable width is ~273mm.
    table = Table(data, colWidths=[32 * mm, 32 * mm, 54 * mm, 24 * mm, 102 * mm, 29 * mm])
    table.repeatRows = 1
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.black),
                ("ALIGN", (0, 0), (-1, 0), "CENTER"),
                ("GRID", (0, 0), (-1, -1), 0.25, colors.grey),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.whitesmoke, colors.white]),
                ("LEFTPADDING", (0, 0), (-1, -1), 4),
                ("RIGHTPADDING", (0, 0), (-1, -1), 4),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ("TOPPADDING", (0, 0), (-1, 0), 6),
                ("BOTTOMPADDING", (0, 0), (-1, 0), 6),
                ("WORDWRAP", (0, 1), (-1, -1), "CJK"),
            ]
        )
    )

    doc.build([
        *header_lines,
        Spacer(1, 6 * mm),
        table,
    ])
    return buffer.getvalue()


def build_order_excel(order: OrderWithItemsOut, workshop_name: str | None = None) -> bytes:
    wb = Workbook()
    ws = wb.active
    ws.title = f"Order {order.id}"

    title = order.order_name or f"Order {order.id}"
    ws.append([workshop_name or ""])
    ws.append([title])
    ws.append([_fmt_date(order.created_at)])
    ws.append([])

    headers = [
        "Manufacturer",
        "Model",
        "Spare Part",
        "Required Quantity",
        "Typical Specification / Note",
        "OEM Part Number",
    ]
    ws.append(headers)

    header_font = Font(bold=True)
    # Top header formatting
    ws.merge_cells(start_row=1, start_column=1, end_row=1, end_column=6)
    ws.merge_cells(start_row=2, start_column=1, end_row=2, end_column=6)
    ws.merge_cells(start_row=3, start_column=1, end_row=3, end_column=6)
    ws["A1"].font = Font(bold=True, size=14)
    ws["A2"].font = Font(bold=True, size=12)
    ws["A3"].font = Font(size=11)
    ws["A1"].alignment = Alignment(horizontal="left", vertical="center", wrap_text=True)
    ws["A2"].alignment = Alignment(horizontal="left", vertical="center", wrap_text=True)
    ws["A3"].alignment = Alignment(horizontal="left", vertical="center", wrap_text=True)

    header_font = Font(bold=True)
    header_row = 5
    for col_idx in range(1, len(headers) + 1):
        cell = ws.cell(row=header_row, column=col_idx)
        cell.font = header_font
        cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)

    ws.freeze_panes = f"A{header_row + 1}"

    for item in sorted(
        order.items,
        key=lambda x: (x.manufacturer_name.lower(), x.model_name.lower(), x.spare_part_name.lower()),
    ):
        ws.append(
            [
                item.manufacturer_name,
                item.model_name,
                item.spare_part_name,
                item.quantity,
                item.typical_specification or "",
                item.oem_part_number or "",
            ]
        )

    ws.column_dimensions["A"].width = 18
    ws.column_dimensions["B"].width = 18
    ws.column_dimensions["C"].width = 28
    ws.column_dimensions["D"].width = 14
    ws.column_dimensions["E"].width = 58
    ws.column_dimensions["F"].width = 22

    for row in ws.iter_rows(min_row=header_row + 1, min_col=4, max_col=4):
        for cell in row:
            cell.alignment = Alignment(horizontal="right", vertical="top")

    for row in ws.iter_rows(min_row=header_row + 1, min_col=1, max_col=3):
        for cell in row:
            cell.alignment = Alignment(wrap_text=True, vertical="top")

    for row in ws.iter_rows(min_row=header_row + 1, min_col=5, max_col=6):
        for cell in row:
            cell.alignment = Alignment(wrap_text=True, vertical="top")

    # Wrap header row too (especially for long columns like Typical Specification).
    for col_idx in range(1, len(headers) + 1):
        cell = ws.cell(row=header_row, column=col_idx)
        cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)

    out = BytesIO()
    wb.save(out)
    return out.getvalue()
